### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by zangiro** [zangiro/app-plan#29]
概要
---
卒業制作、issueベースの開発

内容
---
卒業制作アプリの看板の作成、issueの登録、ストーリーポイントの設定を行いました。
ご確認お願いいます。

以下自分の卒業制作のREADMEなどです。
[README](https://github.com/zangiro/app-plan/pull/1/files)
[画面遷移図](https://www.figma.com/design/fQ8mAXdM7n3zbtiJbPCkt9/%E5%8D%92%E5%88%B6%E4%BD%9C%E7%94%A8?node-id=0-1&node-type=canvas&t=50i2TesWwnUFuRfD-0)
[ER図](https://gyazo.com/a081ab5301dd9bddd6248a4fcffc1b7c)

■Webアプリの概要
### サービス概要
視覚情報優先で、自分の知らないご当地グルメ、郷土料理発見を目的とするアプリです。
### サービスの利用イメージ
１、診断スタートボタンを押す。
２、興味のあるジャンル、地域などを選ぶ。
３、ページに関連するグルメ情報（画像）が出る。
４、画像にカーソルを合わせると軽い紹介文が表示される。
５、クリックで詳細が表示される。
６、現在地を入力すると、その料理が食べられる一番近くのお店への経路情報が出る。

■1週間辺りの開発に向けられる時間
- 1週間あたり：30時間

■ProjectsのURL
[作成したProjects](https://github.com/users/zangiro/projects/2)

■MVPリリースまで
- [ ] rails new
- [ ] ログイン・ログアウト機能
- [ ] トップページ
- [ ] ユーザー新規作成機能
- [ ] ヘッダー作成
- [ ] フッター作成
- [ ] アカウント情報画面
- [ ] 利用規約画面
- [ ] プライバシーポリシー画面
- [ ] お問い合わせ画面
- [ ] パンくずリスト
- [ ] マイページ
- [ ] 画像のアップロード、リサイズ
- [ ] 記事投稿
- [ ] 投稿一覧、投稿削除
- [ ] 投稿編集
- [ ] 記事詳細
- [ ] タグ選択画面
- [ ] 検索による一覧表示
- [ ] パスワード再設定
- [ ] fly.ioにデプロイ

■MVP後
- [ ] プレイリスト機能
- [ ] コメント投稿機能
- [ ] コメント編集・削除
- [ ] いいね機能
- [ ] レコメンデーション
- [ ] あいまい検索
- [ ] おすすめ表示
- [ ] google map APIで経路情報取得
- [ ] 利用規約の内容
- [ ] プライバシーポリシーの内容
- [ ] ページネーション
- [ ] ファビコン
- [ ] CI (GithubActions)

■MVPレビュー依頼予定日
予定日：2024年 12月 7日

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントになります。

---

「デプロイ」に関するissueが見当たらなかったので、ご確認をお願いします。（新規で作成する場合、環境構築後に「デプロイ」のスケージュールを組むのがいいかと思います。）

**Comment by zangiro** [comment]
ご確認ありがとうございます。
projectsに変更を加えました。すみませんが再度ご確認お願いします。
[Projects](https://github.com/users/zangiro/projects/2)

■MVPリリースまで

- [ ] rails new
- [ ] fly.ioにデプロイ
- [ ] ログイン・ログアウト機能
- [ ] トップページ
- [ ] ユーザー新規作成機能
- [ ] ヘッダー作成
- [ ] フッター作成
- [ ] アカウント情報画面
- [ ] 利用規約画面
- [ ] プライバシーポリシー画面
- [ ] お問い合わせ画面
- [ ] パンくずリスト
- [ ] マイページ
- [ ] 画像のアップロード、リサイズ
- [ ] 記事投稿
- [ ] 投稿一覧、投稿削除
- [ ] 投稿編集
- [ ] 記事詳細
- [ ] タグ選択画面
- [ ] 検索による一覧表示
- [ ] パスワード再設定

■MVP後

- [ ] プレイリスト機能
- [ ] コメント投稿機能
- [ ] コメント編集・削除
- [ ] いいね機能
- [ ] レコメンデーション
- [ ] あいまい検索
- [ ] おすすめ表示
- [ ] google map APIで経路情報取得
- [ ] 利用規約の内容
- [ ] プライバシーポリシーの内容
- [ ] ページネーション
- [ ] ファビコン
- [ ] CI (GithubActions)

■MVPレビュー依頼予定日
予定日：2024年 12月 7日

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- パスワード再設定
- タグ
- マイページ
- パンくずリスト
- お問い合わせ
- プライバシーポリシー
- 利用規約

**Comment by zangiro** [comment]
ご確認ありがとうございます。
ご指摘をもとにMVPにおいて削ったほうがよいものを考慮しつつ進めます。
